### ISSUE TITLE
uci module breaks on openwrt 18.06 when --diff is used

### ISSUE THREAD

**Issue by psliwka** [gekmihesg/ansible-openwrt#4]
`uci` module produces quite large output when used in combination with --diff flag. On openwrt 18.06, it seems to trigger some nasty bug in Dropbear, which I've reported in [openwrt bug tracker](https://bugs.openwrt.org/index.php?do=details&task_id=1814).

Opening an issue here to let all `ansible-openwrt` users know about the problem, and possibly gather some workaroud ideas.

Right now, the only workaround I've found is to replace Dropbear with OpenSSH on all devices.

**Comment by gekmihesg** [comment]
I finally managed to do some testing with OpenWRT 18.06. This is really annoying!
On the other hand, the amount of data transmitted by uci was way to much anyway. d956a8d only transmits the output of `uci changes` now. This changes the format, but the information displayed is more or less the same.
