### ISSUE TITLE
ansible_remote_tmp is usually /root, which is bad

### ISSUE THREAD

**Issue by Hurricos** [gekmihesg/ansible-openwrt#58]
Hey there,

Would it be possible to have this role default `ansible_remote_tmp` to `/tmp` instead of `/root`? The default beahvior wears down flash.

I'm not sure if any parts of this role require persistence of files, so I'm not sure if `/tmp` is safe.

**Comment by eroldan** [comment]
Documentation mentions /tmp is the default. https://github.com/gekmihesg/ansible-openwrt#role-variables

**Comment by Hurricos** [comment]
> Documentation mentions /tmp is the default. https://github.com/gekmihesg/ansible-openwrt#role-variables

Thanks for the pointer; you're correct. Adjusting `ansible_remote_tmp` does nothing for the execution of this actual role.

I figured out my issue: I use a playbook to call the role, and the playbook is doing some initial setup under `/root` (leaving a `/root/.ansible/tmp`). Adjusting the playbook vars solves the problem, but would have also fixed this issue if it were really present.
